primechecker: primechecker.c ../pprime_p.c
	gcc primechecker.c -o primechecker -std=c99 -lgmp -I /home/cbright/gmp-5.0.4
debug: primechecker.c ../pprime_p.c
	gcc primechecker.c -o primechecker -std=c99 -lgmp -I /home/cbright/gmp-5.0.4 -g
